# Generated by Django 5.2.8 on 2025-11-15 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "robot_type",
                    models.CharField(
                        choices=[
                            ("welding", "Welding Robot"),
                            ("assembly", "Assembly Robot"),
                            ("painting", "Painting Robot"),
                            ("packaging", "Packaging Robot"),
                            ("inspection", "Inspection Robot"),
                        ],
                        default="assembly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(default="Production Line A", max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "last_maintenance",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_operational_hours", models.FloatField(default=0.0)),
                ("total_units_produced", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RobotData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField(help_text="Temperature in °C")),
                ("vibration", models.FloatField(help_text="Vibration level in mm/s")),
                (
                    "power_consumption",
                    models.FloatField(help_text="Power consumption in kW"),
                ),
                (
                    "efficiency",
                    models.FloatField(help_text="Efficiency percentage 0-100%"),
                ),
                ("units_produced", models.IntegerField(default=0)),
                ("operational_hours", models.FloatField(default=0.0)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="robots.robot",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["robot", "timestamp"],
                        name="robots_robo_robot_i_6637bd_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="robots_robo_timesta_baccdd_idx"
                    ),
                ],
            },
        ),
    ]
